### ISSUE TITLE
vehicle type

### ISSUE THREAD

**Issue by drdanglauber** [digwaybill/Digital-Waybill-API#1]
I'm testing the API to use on one of our projects, but can't find any documentation that describes what values are allowed for the following error: 

{"status":400,"error":"Value `' for attribute `vehicle' is not a valid vehicle.","body":""}

**Comment by aegeus24** [comment]
Hi Dan,

The vehicle values are defined by the courier company you are working with in their copy of Digital Waybill. If they do not make use of vehicle types the value should be an empty string. 

If you still run into issues, can you let me know which company you are working with and add an example your POST?

**Comment by drdanglauber** [comment]
Thanks for getting back to me.  Currently I'm testing out the API to
incorporate with our pharmacy system.  The company is called Trax and I
believe the CID is 2000072260.

I don't see any vehicle types in their setup, plus they said they don't use
this.


Thank you,
Dr. Daniel Glauber
(817) 876-7868

**Comment by sfxgg** [comment]
Hi Daniel,

Can you share the POST request you're making?

**Comment by drdanglauber** [comment]
I got it working. Instead of having a blank value for vehicle, I removed it. Seems to be working great. 

Thanks!
