### ISSUE TITLE
Update Documentation for Supporting the service_types.json GET Request

### ISSUE THREAD

**Issue by sfxgg** [digwaybill/Digital-Waybill-API#3]
Similar to #2 

A GET request formatted as follows returns the service types existing on the main panel within a JSON array under the service_types key inside the body of the response:

`https://api.dwaybill.com/{CID_HERE}/service_types.json?v=1&key={API_KEY_HERE}`

The GET request also works if using the Quick Entry API Key along with a customer number and password for a specific customer. One thing to note is that this returns _all_ of the service types that currently exist in the database. Not just the subset of service types allowed to a customer.

`https://api.dwaybill.com/{CID_HERE}/service_types.json?v=1&key={API_KEY_HERE}&customer_number={CUSTOMER_NUMBER_HERE}&password={CUSTOMER_PASSWORD_HERE}`

**Comment by aegeus24** [comment]
This is already on the readme.
